name: bio
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - snakemake
  - fastqc
  - star
  - rsem
  - trimmomatic
  - qualimap
  - conda-forge::ncurses
  - bioconda::samtools
  - snakemake-wrapper-utils
  - samtools
pip:
  - matplotlib
  - scipy
  - scikit-learn
  - seaborn
  - jupyterlab